### ISSUE TITLE
Error: Failed to serialize user into session

### ISSUE THREAD

**Issue by Kikobeats** [sailorjs/sailor-module-user#1]
Exist a little problem when you want to use a custom controller action (like login or logout)

![](http://i.imgur.com/hNZIlUz.png)

I don't know why this happens. I'm not a Passport expert, but this module is a [sails-generate-auth-port](https://github.com/kasperisager/sails-generate-auth) and here it works and there it doesn't. I'm break something!

I know that the problem is [Passport.Callback](https://github.com/sailorjs/sailor-module-user/blob/master/api/services/passport.coffee#L142). Maybe @kasperisager or @albertosouza can help me in this aspect.

Of course I have serializer and deserializer function. Something wrong?

**Comment by Kikobeats** [comment]
fixed!

**Comment by albertosouza** [comment]
good, :)
